# Proyecto 1: Explorando Datos del Mundo Real con Python

**Carrera:** Tecnicatura Universitaria en Tecnologías de Programación

**Materia:** Programación Python Avanzada

**Integrantes:** Olivera Yohana y Urriola Itziar

**Dataset:** Juegos de la tienda Steam 

**Fuente:** Kaggle.com

**Link Dataset:** https://www.kaggle.com/datasets/nikdavis/steam-store-games

**Link Repositorio GitHub:** https://github.com/YohaOlivera/Proyecto1_Olivera_Urriola_UPSO-Salliquelo

## Análisis exploratorio del catálogo de videojuegos de Steam (1997–2019)

### Descripción del dataset

Este dataset proporciona información detallada sobre los juegos disponibles en la tienda de Steam, creada a partir de datos recopilados mediante las API de Steam Store y SteamSpy. Contiene un registro de 27.075 filas y 18 columnas abarcando videojuegos desde inicio del 1997 hasta mediados del 2019.
La base recopila variables comerciales e identificatorias (nombre, fecha de lanzamiento, desarrollador, editor y precio de venta base), especificaciones técnicas (compatibilidad de sistemas operativos y géneros), y métricas de recepción comunitaria (recuento de reseñas positivas y negativas, cantidad de logros y tiempos promedio de juego registrados por los usuarios).


### Justificación de la elección

Se eligió este dataset porque además de cumplir con las condiciones que se piden para este proyecto,
nos resulto interesante analizar este dataset sobre videojuegos ya que es un hobbie que compartimos entre ambas.


### Preguntas de investigación

Al analizar el contenido del dataset, nos surgieron las siguientes preguntas para responder con los datos del dataset:

1. ¿Que genero de videojuego concentra el mayor porcentaje promedio de reseñas positivas por parte de los usuarios? 

2. ¿Existen una relación directa o correlación lineal entre el precio de un videojuego y el nivel de satisfacción de los jugadores?

3. ¿En que período anual se produjo la mayor aceleración histórica en la cantidad de lanzamientos dentro de la plataforma Steam?

### Diccionario de variables

| Columna | Tipo de Dato | Descripción |
|--------|--------------|-------------|
| Id juego | int64 | Identificador único del videojuego en la plataforma Steam. |
| Nombre | object (str) | Título oficial del videojuego. |
| Fecha de lanzamiento | object (str) | Fecha en la que el juego fue publicado en la tienda. |
| Idioma ingles | int64 | Variable binaria: 1 si el juego incluye soporte para idioma inglés, 0 en caso contrario. |
| Desarrollador | object (str) | Estudio o persona creadora del videojuego. |
| Editor | object (str) | Empresa encargada de la publicación y distribución comercial del título. |
| Plataformas | object (str) | Sistemas operativos compatibles (ej. windows, mac, linux). |
| Edad requerida | int64 | Edad mínima recomendada o restricción de edad oficial. |
| Categorias | object (str) | Modos de juego y características técnicas (ej. Single-player, Multi-player). |
| Generos | object (str) | Clasificación temática principal del juego (ej. Action, Adventure, Indie). |
| Etiquetas SteamSpy | object (str) | Etiquetas asignadas por la comunidad de jugadores en la plataforma SteamSpy. |
| Logros | int64 | Cantidad total de logros (achievements) desbloqueables en el juego. |
| Valoraciones positivas | int64 | Cantidad total de reseñas positivas recibidas por parte de los usuarios. |
| Valoraciones negativas | int64 | Cantidad total de reseñas negativas recibidas por parte de los usuarios. |
| Tiempo promedio de juego | int64 | Tiempo promedio de juego registrado por los usuarios (expresado en minutos). |
| Tiempo medio de juego | int64 | Mediana del tiempo de juego de la base de usuarios (expresado en minutos). |
| Propietarios | object (str) | Rango estimado de usuarios que poseen el juego en su biblioteca. |
| Precio | float64 | Precio de venta base original (en Libras Esterlinas - GBP). |

### Desarrollo

#### Importación de librerías y exploración inicial

In [28]:
# Importamos las librerías
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Cargamos el dataset
df_original = pd.read_csv("steam.csv")

Generamos una copia del dataset para hacer el análisis sin alterar los datos originales.

In [29]:
df = df_original.copy()

Transformamos los nombres de las columnas al español, para facilitar el uso y el análisis

In [30]:
nuevos_nombres = {
    "appid": "Id juego",
    "name": "Nombre",
    "release_date": "Fecha de lanzamiento",
    "developer": "Desarrollador",
    "publisher": "Editor",
    "platforms": "Plataformas",
    "required_age": "Edad requerida",
    "categories": "Categorias",
    "genres": "Generos",
    "achievements": "Logros",
    "positive_ratings": "Valoraciones positivas",
    "negative_ratings": "Valoraciones negativas",
    "average_playtime": "Tiempo promedio de juego",
    "median_playtime": "Tiempo medio de juego",
    "owners": "Propietarios",
    "price": "Precio",
    "english": "Idioma ingles",
    "steamspy_tags": "Etiquetas SteamSpy"
}

df = df.rename(columns=nuevos_nombres)

print(df.columns.tolist())
df.head()

['Id juego', 'Nombre', 'Fecha de lanzamiento', 'Idioma ingles', 'Desarrollador', 'Editor', 'Plataformas', 'Edad requerida', 'Categorias', 'Generos', 'Etiquetas SteamSpy', 'Logros', 'Valoraciones positivas', 'Valoraciones negativas', 'Tiempo promedio de juego', 'Tiempo medio de juego', 'Propietarios', 'Precio']

,Id juego,Nombre,Fecha de lanzamiento,Idioma ingles,Desarrollador,Editor,Plataformas,Edad requerida,Categorias,Generos,Etiquetas SteamSpy,Logros,Valoraciones positivas,Valoraciones negativas,Tiempo promedio de juego,Tiempo medio de juego,Propietarios,Precio
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99

Utilizamos **`.shape[ ]`** para conocer las dimensiones del dataset, es decir cuantas filas y columnas tiene.

In [ ]:
print(f"Dimensiones del dataset: {df.shape[0]} filas y {df.shape[1]} columnas")

Dimensiones del dataset: 27075 filas y 18 columnas

Con el método **`.info( )`** obtenemos el nombre de las columnas, un conteo de valores NO nulos y el tipo de dato que contiene cada columna.

In [19]:
print("Información general y tipos de datos:")
df.info()

Información general y tipos de datos:
<class 'pandas.DataFrame'>
RangeIndex: 27075 entries, 0 to 27074
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id juego                  27075 non-null  int64
 1   Nombre                    27075 non-null  str
 2   Fecha de lanzamiento      27075 non-null  str
 3   Idioma ingles             27075 non-null  int64
 4   Desarrollador             27074 non-null  str
 5   Editor                    27061 non-null  str
 6   Plataformas               27075 non-null  str
 7   Edad requerida            27075 non-null  int64
 8   Categorias                27075 non-null  str
 9   Generos                   27075 non-null  str
 10  Etiquetas SteamSpy        27075 non-null  str
 11  Logros                    27075 non-null  int64
 12  Valoraciones positivas    27075 non-null  int64
 13  Valoraciones negativas    27075 non-null  int64
 14  Tiempo promedio de juego  27075 non-null  int64
 15  Tiempo medio de juego     27075 non-null  int64
 16  Propietarios              27075 non-null  str
 17  Precio                    27075 non-null  float64
dtypes: float64(1), int64(8), str(9)
memory usage: 3.7 MB

En la información anterior notamos que:

* Las columnas "Desarrollador" y "Editor" no contienen la totalidad de los datos, por lo cual inferimos que hay valores nulos. Para comprobarlo ejecutamos el siguiente código:

In [31]:
# Mostramos las columnas con valores nulos
print("Columnas con valores nulos:")
nulos = df.isnull().sum()
nulos[nulos > 0]

Columnas con valores nulos:

Desarrollador     1
Editor           14
dtype: int64

Calculamos que porcentaje representan estos valores sobre el total de los datos.

In [32]:
# Mostramos el porcentaje de valores nulos por columna
print("Porcentaje de valores nulos (%):")
porcentaje_nulos = (nulos[nulos > 0] / len(df)) * 100
porcentaje_nulos.round(4)

Porcentaje de valores nulos (%):

Desarrollador    0.0037
Editor           0.0517
dtype: float64

Exploramos de manera inicial las estadísticas de las variables numéricas

In [33]:
print("Estadísticas dscriptivas de variables numéricas:")
df.describe()

Estadísticas dscriptivas de variables numéricas:

,Id juego,Idioma ingles,Edad requerida,Logros,Valoraciones positivas,Valoraciones negativas,Tiempo promedio de juego,Tiempo medio de juego,Precio
count,2.707500e+04,27075.000000,27075.000000,27075.000000,2.707500e+04,27075.000000,27075.000000,27075.00000,27075.000000
mean,5.962035e+05,0.981127,0.354903,45.248864,1.000559e+03,211.027147,149.804949,146.05603,6.078193
std,2.508942e+05,0.136081,2.406044,352.670281,1.898872e+04,4284.938531,1827.038141,2353.88008,7.874922
min,1.000000e+01,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.00000,0.000000
25%,4.012300e+05,1.000000,0.000000,0.000000,6.000000e+00,2.000000,0.000000,0.00000,1.690000
50%,5.990700e+05,1.000000,0.000000,7.000000,2.400000e+01,9.000000,0.000000,0.00000,3.990000
75%,7.987600e+05,1.000000,0.000000,23.000000,1.260000e+02,42.000000,0.000000,0.00000,7.190000
max,1.069460e+06,1.000000,18.000000,9821.000000,2.644404e+06,487076.000000,190625.000000,190625.00000,421.990000

**Conclusión sobre la calidad de datos:**

* Como muestra la exploración inicial el dataset es robusto ya que cuenta con un total de 27.075 registros. 
* Los tipos de datos son coherentes con la información que representan en la mayoría de las columnas, aunque variables como la "Fecha de lanzamiento" requieren transformación a formato datetime para su correcto análisis temporal. 
* A nivel de completitud, consideramos que tiene una alta calidad, únicamente se detectaron valores nulos en las columnas categóricas "Desarrollador" (1 nulo) y "Editor" (14 nulos). Al representar un porcentaje ínfimo respecto al total (menos del 0,05%), requerirán un tratamiento de limpieza menor sin comprometer la integridad del análisis general.

#### Variables Categóricas y Numéricas a analizar

Para poder dar respuesta a las preguntas de investigación que nos planteamos en este proyecto, seleccionamos las siguientes variables clave:

* **Variables Numéricas:**
    * **Precio:** Es la variable principal para analizar si el costo monetario guarda relación con la recepción del público
    * **Valoraciones positivas y negativas:** Ambas variables son necesarias para construir una métrica de satisfacción del usuario y medir el porcentaje de aceptación.

* **Variables Categóricas:**
    * **Genero:** Esta variable resulta imprescindible para clasificar el catálogo y descubrir qué tipo de juegos concentra las mejores reseñas.
    * **Fecha de lanzamiento:** Clave para evaluar el crecimiento histórico del catálogo y detectar el período de mayor aceleración de publicaciones.
    * **Plataformas:** Esta variable nos permite segmentar el mercado permitiendo evaluarel impacto del soporte multiplataforma en relación a las politicas de precios y en la satisfacción de los usuarios.

#### Transformaciones y limpieza de datos

* **Manejo de valores faltantes**

Al inspeccionar el dataset, detectamos valores nulos en dos columanas.Como representan un porcentaje minusculo (0,0037 y 0,0517)tomamos la decisión de eliminar estas filas, ya que imputar los datos con otros valores no genera un aporte significativo al análisis

In [34]:
# Eliminamos las filas con nulos en Desarollador y Editor
df = df.dropna(subset=["Desarrollador", "Editor"]).copy()

# Comprobamos las nuevas dimensiones 
print(f"Dimensiones del dataset tras eliminar nulos: {df.shape}")

Dimensiones del dataset tras eliminar nulos: (27061, 18)

* **Limpieza y creacion de nuevas columnas**

Para responder nuestras preguntas de investigación, realizamos las siguientes transformaciones:

* **Género principal:** En el dataset los juegos tienen múltiples géneros separados por punto y coma (ej: Action;Adventure). Extraeremos solo el primero para categorizarlos mejor.

In [41]:
# Eliminamos los espacios en blanco de la columna "Generos"
df["Generos"] = df["Generos"].astype(str).str.strip()

# Extraemos el genero principal
df["Genero principal"] = df["Generos"].str.split(";").str[0].str.strip()

# Ver los generos principales más comunes
print("Distribucion de generos principales:")
df["Genero principal"].value_counts().head(10)

Distribucion de generos principales:

Genero principal
Action            11205
Adventure          5254
Casual             4371
Indie              2622
Violent             708
Simulation          630
Strategy            532
RPG                 407
Free to Play        395
Sexual Content      245
Name: count, dtype: int64

* **Plataformas:** Separamos en columnas binarias cada una de las plataformas, ya que nos permite hacer cálculos.

In [42]:
# Creamos nuevas columnas binarias para cada plataforma
df["Plataforma Windows"] = df["Plataformas"].str.contains("windows", case=False).astype(int)
df["Plataforma Mac"] = df["Plataformas"].str.contains("mac", case=False).astype(int)
df["Plataforma Linux"] = df["Plataformas"].str.contains("linux", case=False).astype(int)

# Creamos una nueva columna que cuente la cantidad de plataformas disponibles para cada juego
df["Cantidad plataformas"] = df["Plataforma Windows"] + df["Plataforma Mac"] + df["Plataforma Linux"]

# Verificación
df[["Nombre", "Plataformas", "Plataforma Windows", "Plataforma Mac", "Plataforma Linux", "Cantidad plataformas"]].head()

,Nombre,Plataformas,Plataforma Windows,Plataforma Mac,Plataforma Linux,Cantidad plataformas
0,Counter-Strike,windows;mac;linux,1,1,1,3
1,Team Fortress Classic,windows;mac;linux,1,1,1,3
2,Day of Defeat,windows;mac;linux,1,1,1,3
3,Deathmatch Classic,windows;mac;linux,1,1,1,3
4,Half-Life: Opposing Force,windows;mac;linux,1,1,1,3

* **Precios en USD:** Transformaremos la moneda original (GBP) a dólares asumiendo una tasa de cambio fija aproximada (1 GBP = 1.30 USD).

In [38]:
tasa_cambio_gbp_usd = 1.30
df["Precio usd"] = (df["Precio"] * tasa_cambio_gbp_usd).round(2)

df.info()

<class 'pandas.DataFrame'>
Index: 27061 entries, 0 to 27074
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id juego                  27061 non-null  int64
 1   Nombre                    27061 non-null  str
 2   Fecha de lanzamiento      27061 non-null  str
 3   Idioma ingles             27061 non-null  int64
 4   Desarrollador             27061 non-null  str
 5   Editor                    27061 non-null  str
 6   Plataformas               27061 non-null  str
 7   Edad requerida            27061 non-null  int64
 8   Categorias                27061 non-null  str
 9   Generos                   27061 non-null  str
 10  Etiquetas SteamSpy        27061 non-null  str
 11  Logros                    27061 non-null  int64
 12  Valoraciones positivas    27061 non-null  int64
 13  Valoraciones negativas    27061 non-null  int64
 14  Tiempo promedio de juego  27061 non-null  int64
 15  Tiempo medio de juego     27061 non-null  int64
 16  Propietarios              27061 non-null  str
 17  Precio                    27061 non-null  float64
 18  Genero principal          27061 non-null  object
 19  Precio usd                27061 non-null  float64
 20  Plataforma Windows        27061 non-null  int64
 21  Plataforma Mac            27061 non-null  int64
 22  Plataforma Linux          27061 non-null  int64
 23  Cantidad plataformas      27061 non-null  int64
dtypes: float64(2), int64(12), object(1), str(9)
memory usage: 5.2+ MB

* **índice de satidfacción:** Calculamos la proporción de valoraciones positivas sobre el total de valoraciones: Positivas / (Positivas + Negativas).

In [ ]:
total_valoraciones = df['Valoraciones positivas'] + df['Valoraciones negativas']

# Creamos la columna vacía
df['Indice de satisfaccion'] = np.nan

# Calculamos solo donde hay votos registrados
con_votos = total_valoraciones > 0
df.loc[con_votos, 'Indice de satisfaccion'] = (
    df.loc[con_votos, 'Valoraciones positivas'] / total_valoraciones[con_votos]
).round(4)

# Verificación
df[["Nombre", "Valoraciones positivas", "Valoraciones negativas", "Indice de satisfaccion"]].head()

,Nombre,Valoraciones positivas,Valoraciones negativas,Indice de satisfaccion
0,Counter-Strike,124534,3339,0.9739
1,Team Fortress Classic,3318,633,0.8398
2,Day of Defeat,3416,398,0.8956
3,Deathmatch Classic,1273,267,0.8266
4,Half-Life: Opposing Force,5250,288,0.9480

Para facilitar la comprensión conveetimos en porcentaje el índice de valoración

In [43]:
df["Porcentaje satisfaccion"] = np.nan
con_votos = total_valoraciones > 0

df.loc[con_votos, "Porcentaje satisfaccion"] = (
    (df.loc[con_votos, "Valoraciones positivas"] / total_valoraciones.loc[con_votos]) * 100
).round(2)

# Verificación
df[["Nombre", "Valoraciones positivas", "Valoraciones negativas", "Porcentaje satisfaccion"]].head()

,Nombre,Valoraciones positivas,Valoraciones negativas,Porcentaje satisfaccion
0,Counter-Strike,124534,3339,97.39
1,Team Fortress Classic,3318,633,83.98
2,Day of Defeat,3416,398,89.56
3,Deathmatch Classic,1273,267,82.66
4,Half-Life: Opposing Force,5250,288,94.80

* **Rango de precios:** Clasificamos los juegos en Gratis, Económico, Estándar y Premium usando la función `pd.cut`.

* **Año de lanzamiento:** Extraemos solo el año de la fecha completa.

Agrupación por variable categorica

#### Operaciones con NumPy

Normalización de las variables

#### Visualización de datos

#### Conlusiones

#### Exportación de resultados