# Proyecto 1: Explorando Datos del Mundo Real con Python

**Carrera:** Tecnicatura Universitaria en Tecnologías de Programación

**Materia:** Programación Python Avanzada

**Integrantes:** Olivera Yohana y Urriola Itziar

**Dataset:** Juegos de la tienda Steam 

**Fuente:** Kaggle.com

**Link Dataset:** https://www.kaggle.com/datasets/nikdavis/steam-store-games

**Link Repositorio GitHub:** https://github.com/YohaOlivera/Proyecto1_Olivera_Urriola_UPSO-Salliquelo

## Análisis de ventas globales de videojuegos

### Descripción del dataset

Este dataset proporciona información detallada sobre los juegos disponibles en la tienda de Steam, creada a partir de datos recopilados mediante las API de Steam Store y SteamSpy. Contiene un registro de 27.075 filas y 18 columnas abarcando videojuegos desde inicio del 1997 hasta mediados del 2019.
La base recopila variables comerciales e identificatorias (nombre, fecha de lanzamiento, desarrollador, editor y precio de venta base), especificaciones técnicas (compatibilidad de sistemas operativos y géneros), y métricas de recepción comunitaria (recuento de reseñas positivas y negativas, cantidad de logros y tiempos promedio de juego registrados por los usuarios).


### Justificación de la elección

Se eligió este dataset porque además de cumplir con las condiciones que se piden para este proyecto,
nos resulto interesante analizar este dataset sobre videojuegos ya que es un hobbie que compartimos entre ambas.


### Preguntas de investigación

Al analizar el contenido del dataset, nos surgieron las siguientes preguntas para responder con los datos del dataset:

1. ¿Que genero de videojuego concentra el mayor porcentaje promedio de reseñas positivas por parte de los usuarios? 

2. ¿Existen una relación directa o correlación lineal entre el precio de un videojuego y el nivel de satisfacción de los jugadores?

3. ¿En que período anual se produjo la mayor aceleración histórica en la cantidad de lanzamientos dentro de la plataforma Steam?

### Diccionario de variables

### Código

#### Carga y exploración inicial

In [15]:
# Importamos las librerías
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Cargamos el dataset
df_original = pd.read_csv("steam.csv")

Generamos una copia del dataset para hacer el análisis sin alterar los datos originales.

In [16]:
df = df_original.copy()

Transformamos los nombres de las columnas al español, para facilitar el uso y el análisis

In [17]:
nuevos_nombres = {
    "appid": "Id juego",
    "name": "Nombre",
    "release_date": "Fecha de lanzamiento",
    "developer": "Desarrollador",
    "publisher": "Editor",
    "platforms": "Plataformas",
    "required_age": "Edad requerida",
    "categories": "Categorias",
    "genres": "Generos",
    "achievements": "Logros",
    "positive_ratings": "Valoraciones positivas",
    "negative_ratings": "Valoraciones negativas",
    "average_playtime": "Tiempo promedio de juego",
    "median_playtime": "Tiempo medio de juego",
    "owners": "Propietarios",
    "price": "Precio",
    "english": "Idioma ingles",
    "steamspy_tags": "Etiquetas SteamSpy"
}

df = df.rename(columns=nuevos_nombres)

print(df.columns.tolist())
df.head()

['Id juego', 'Nombre', 'Fecha de lanzamiento', 'Idioma ingles', 'Desarrollador', 'Editor', 'Plataformas', 'Edad requerida', 'Categorias', 'Generos', 'Etiquetas SteamSpy', 'Logros', 'Valoraciones positivas', 'Valoraciones negativas', 'Tiempo promedio de juego', 'Tiempo medio de juego', 'Propietarios', 'Precio']

,Id juego,Nombre,Fecha de lanzamiento,Idioma ingles,Desarrollador,Editor,Plataformas,Edad requerida,Categorias,Generos,Etiquetas SteamSpy,Logros,Valoraciones positivas,Valoraciones negativas,Tiempo promedio de juego,Tiempo medio de juego,Propietarios,Precio
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99

Utilizamos **`.shape[ ]`** para conocer las dimensiones del dataset, es decir cuantas filas y columnas tiene.

In [18]:
# Exploracion inicial
print(f"Dimensiones del dataset: {df.shape[0]} filas y {df.shape[1]} columnas")

Dimensiones del dataset: 27075 filas y 18 columnas

Con el método **`.info( )`** obtenemos el nombre de las columnas, un conteo de valores NO nulos y el tipo de dato que contiene cada columna.

In [19]:
print("Información general y tipos de datos:")
df.info()

Información general y tipos de datos:
<class 'pandas.DataFrame'>
RangeIndex: 27075 entries, 0 to 27074
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id juego                  27075 non-null  int64
 1   Nombre                    27075 non-null  str
 2   Fecha de lanzamiento      27075 non-null  str
 3   Idioma ingles             27075 non-null  int64
 4   Desarrollador             27074 non-null  str
 5   Editor                    27061 non-null  str
 6   Plataformas               27075 non-null  str
 7   Edad requerida            27075 non-null  int64
 8   Categorias                27075 non-null  str
 9   Generos                   27075 non-null  str
 10  Etiquetas SteamSpy        27075 non-null  str
 11  Logros                    27075 non-null  int64
 12  Valoraciones positivas    27075 non-null  int64
 13  Valoraciones negativas    27075 non-null  int64
 14  Tiempo promedio de juego  27075 non-null  int64
 15  Tiempo medio de juego     27075 non-null  int64
 16  Propietarios              27075 non-null  str
 17  Precio                    27075 non-null  float64
dtypes: float64(1), int64(8), str(9)
memory usage: 3.7 MB

En la información anterior notamos que:

* Las columnas "Desarrollador" y "Editor" no contienen la totalidad de los datos, por lo cual inferimos que hay valores nulos. Para comprobarlo ejecutamos el siguiente código:

In [20]:
print("Columnas con valores nulos:")
nulos = df.isnull().sum()
nulos[nulos > 0]

Columnas con valores nulos:

Desarrollador     1
Editor           14
dtype: int64

Exploramos de manera inicial las estadísticas de las variables numéricas

In [21]:
print("Estadísticas dscriptivas de variables numéricas:")
df.describe()

Estadísticas dscriptivas de variables numéricas:

,Id juego,Idioma ingles,Edad requerida,Logros,Valoraciones positivas,Valoraciones negativas,Tiempo promedio de juego,Tiempo medio de juego,Precio
count,2.707500e+04,27075.000000,27075.000000,27075.000000,2.707500e+04,27075.000000,27075.000000,27075.00000,27075.000000
mean,5.962035e+05,0.981127,0.354903,45.248864,1.000559e+03,211.027147,149.804949,146.05603,6.078193
std,2.508942e+05,0.136081,2.406044,352.670281,1.898872e+04,4284.938531,1827.038141,2353.88008,7.874922
min,1.000000e+01,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.00000,0.000000
25%,4.012300e+05,1.000000,0.000000,0.000000,6.000000e+00,2.000000,0.000000,0.00000,1.690000
50%,5.990700e+05,1.000000,0.000000,7.000000,2.400000e+01,9.000000,0.000000,0.00000,3.990000
75%,7.987600e+05,1.000000,0.000000,23.000000,1.260000e+02,42.000000,0.000000,0.00000,7.190000
max,1.069460e+06,1.000000,18.000000,9821.000000,2.644404e+06,487076.000000,190625.000000,190625.00000,421.990000

#### Variables Categóricas y Numéricas a analizar

VARIABLES NUMÉRICAS:
* Precio
* Valoraciones positivas
* Valoraciones negativas

VARIABLES CATEGÓRICAS:
* Genero
* Fecha de lanzamiento
* Plataformas

#### Normalización de las variables

Como la variable precio esta en libras esterlinas (GBP), decidimos convertirla a dolar norteamericano (USD), y usaremos esta nueva columna para nuestro análisis

In [22]:
tasa_cambio_gbp_usd = 1.30
df["Precio usd"] = (df["Precio"] * tasa_cambio_gbp_usd).round(2)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27075 entries, 0 to 27074
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id juego                  27075 non-null  int64
 1   Nombre                    27075 non-null  str
 2   Fecha de lanzamiento      27075 non-null  str
 3   Idioma ingles             27075 non-null  int64
 4   Desarrollador             27074 non-null  str
 5   Editor                    27061 non-null  str
 6   Plataformas               27075 non-null  str
 7   Edad requerida            27075 non-null  int64
 8   Categorias                27075 non-null  str
 9   Generos                   27075 non-null  str
 10  Etiquetas SteamSpy        27075 non-null  str
 11  Logros                    27075 non-null  int64
 12  Valoraciones positivas    27075 non-null  int64
 13  Valoraciones negativas    27075 non-null  int64
 14  Tiempo promedio de juego  27075 non-null  int64
 15  Tiempo medio de juego     27075 non-null  int64
 16  Propietarios              27075 non-null  str
 17  Precio                    27075 non-null  float64
 18  Precio usd                27075 non-null  float64
dtypes: float64(2), int64(8), str(9)
memory usage: 3.9 MB

In [23]:
# Eliminamos los espacios en blanco de la columna "Generos"
df["Generos"] = df["Generos"].astype(str).str.strip()

# Extraemos el genero principal
df["Genero principal"] = df["Generos"].str.split(";").str[0].str.strip()

# Ver los generos principales más comunes
print("Distribucion de generos principales:")
print(df["Genero principal"].value_counts().head(10))

Distribucion de generos principales:
Genero principal
Action            11212
Adventure          5256
Casual             4373
Indie              2623
Violent             709
Simulation          631
Strategy            532
RPG                 407
Free to Play        395
Sexual Content      245
Name: count, dtype: int64